data:
  path: ../data/YoutubeCommentsDataSet.csv
  split_ratio: 0.8
  experiment_name: sentiment_analysis_test_4

model:
  embedding_dim: 128
  hidden_dim: 64
  dropout: 0.3

training:
  n_epochs: 10
  batch_size: 64
  embed_size: 256
  lstm_units: 256
  learning_rate: 0.001
